version: '2'

services:
  coreykepple:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/
    ports:
      - '8080:80'
    entrypoint: /var/www/entrypoint.sh -d
